//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STROYMELL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banks
    {
        public int ID_Bank { get; set; }
        public string Title { get; set; }
        public string WebSite { get; set; }
    }
}
