//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STROYMELL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundsWithdrawals
    {
        public int ID_FundsWithdrawl { get; set; }
        public string TypeTransaction { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> ID_Transaction { get; set; }
    
        public virtual Transactions Transactions { get; set; }
    }
}
