//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STROYMELL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostoryMatches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HostoryMatches()
        {
            this.HistoryRounds = new HashSet<HistoryRounds>();
        }
    
        public int ID_HistoryMatch { get; set; }
        public Nullable<double> TotalWins { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_Match { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryRounds> HistoryRounds { get; set; }
        public virtual Matches Matches { get; set; }
        public virtual Users Users { get; set; }
    }
}
