//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STROYMELL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class casinoEntities : DbContext
    {
        public casinoEntities()
            : base("name=casinoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banks> Banks { get; set; }
        public virtual DbSet<FundsDeposits> FundsDeposits { get; set; }
        public virtual DbSet<FundsWithdrawals> FundsWithdrawals { get; set; }
        public virtual DbSet<HistoryRounds> HistoryRounds { get; set; }
        public virtual DbSet<HostoryMatches> HostoryMatches { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Rounds> Rounds { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
