//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STROYMELL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ID_Report { get; set; }
        public string ReportType { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
